import { Feature } from '@/types';

export const FEATURES: Feature[] = [
  {
    id: 'base_site',
    name: 'Base Website Setup',
    category: 'pages',
    min_cost: 40000,
    max_cost: 60000,
    dev_hours: 24,
    complexity: 'low',
    dependencies: [],
    is_optional: false,
    is_default: true,
    is_enabled: true,
    description: 'Mandatory standard responsive architecture with navigation, contact info, and basic layouts.'
  },
  {
    id: 'eco_cart',
    name: 'Add to Cart System',
    category: 'ecommerce',
    min_cost: 12000,
    max_cost: 18000,
    dev_hours: 10,
    complexity: 'low',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Shopping cart drawer allowing visitors to add multiple products and compile orders.'
  },
  {
    id: 'pay_online',
    name: 'Online Payments integration',
    category: 'gateway',
    min_cost: 15000,
    max_cost: 22000,
    dev_hours: 12,
    complexity: 'medium',
    dependencies: ['eco_cart'],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Stripe, Razorpay, or PhonePe checkout gateway integrating card, UPI, and net banking routes.'
  },
  {
    id: 'pay_cod',
    name: 'Cash on Delivery checkout',
    category: 'gateway',
    min_cost: 4000,
    max_cost: 6000,
    dev_hours: 4,
    complexity: 'low',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Calculates specific cash order verification rules and cash checkout processing fields.'
  },
  {
    id: 'chk_auth',
    name: 'Customer Login / Signup',
    category: 'checkout',
    min_cost: 12000,
    max_cost: 18000,
    dev_hours: 12,
    complexity: 'medium',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Secure customer profiles portal enabling email authentication and order history access.'
  },
  {
    id: 'eco_wishlist',
    name: 'Wishlist features',
    category: 'ecommerce',
    min_cost: 6000,
    max_cost: 10000,
    dev_hours: 6,
    complexity: 'low',
    dependencies: ['chk_auth'],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Enable customers to save products to a customized favorites list for future purchasing.'
  },
  {
    id: 'eco_reviews',
    name: 'Product Reviews & Ratings',
    category: 'ecommerce',
    min_cost: 10000,
    max_cost: 14000,
    dev_hours: 8,
    complexity: 'medium',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Interactive client review threads with rating averages and review moderations.'
  },
  {
    id: 'eco_coupons',
    name: 'Coupon Codes & Discounts',
    category: 'ecommerce',
    min_cost: 8000,
    max_cost: 12000,
    dev_hours: 8,
    complexity: 'medium',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Configure and validate custom percentage or flat discount coupon keys during checkout.'
  },
  {
    id: 'ship_tracking',
    name: 'Order Tracking details',
    category: 'shipping',
    min_cost: 12000,
    max_cost: 18000,
    dev_hours: 10,
    complexity: 'medium',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Logs live courier updates and renders tracking checkposts directly to customer profiles.'
  },
  {
    id: 'nav_search',
    name: 'Interactive Search Bar',
    category: 'pages',
    min_cost: 5000,
    max_cost: 8000,
    dev_hours: 4,
    complexity: 'low',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Instant site-wide keywords index search finding pages or products rapidly.'
  },
  {
    id: 'nav_filters',
    name: 'Category Catalog Filters',
    category: 'pages',
    min_cost: 8000,
    max_cost: 12000,
    dev_hours: 6,
    complexity: 'low',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Filter items by attributes, pricing ranges, and sorting keys.'
  },
  {
    id: 'eco_related',
    name: 'Related Products widgets',
    category: 'ecommerce',
    min_cost: 6000,
    max_cost: 10000,
    dev_hours: 6,
    complexity: 'low',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Automated related item grids presented at the footer of product viewports.'
  },
  {
    id: 'page_blog',
    name: 'Blog module',
    category: 'pages',
    min_cost: 10000,
    max_cost: 15000,
    dev_hours: 8,
    complexity: 'medium',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Custom content publishing stream with articles listing, categorizing and sharing layouts.'
  },
  {
    id: 'page_faq',
    name: 'Interactive FAQ accordions',
    category: 'pages',
    min_cost: 3000,
    max_cost: 5000,
    dev_hours: 3,
    complexity: 'low',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Categorized accordion blocks resolving major user doubts.'
  },
  {
    id: 'mkt_whatsapp',
    name: 'WhatsApp Floating Chat button',
    category: 'marketing',
    min_cost: 2000,
    max_cost: 4000,
    dev_hours: 2,
    complexity: 'low',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Floating chat widget redirecting visitors to start WhatsApp chats with support.'
  },

  {
    id: 'sys_multilang',
    name: 'Multi-Language translations',
    category: 'advanced',
    min_cost: 15000,
    max_cost: 22000,
    dev_hours: 15,
    complexity: 'high',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Toggle visual content translations across multiple language choices.'
  },
  {
    id: 'chk_gst_invoice',
    name: 'GST invoice generation',
    category: 'checkout',
    min_cost: 8000,
    max_cost: 12000,
    dev_hours: 6,
    complexity: 'medium',
    dependencies: [],
    is_optional: true,
    is_default: false,
    is_enabled: true,
    description: 'Calculates corporate GST inputs and automatically exports structured tax details.'
  }
];

export const CATEGORIES_LABELS: Record<string, string> = {
  pages: 'Core Essentials & Blog',
  ecommerce: 'E-Commerce Features',
  checkout: 'Checkout & Corporate GST',
  gateway: 'Payment Gateways',
  shipping: 'Shipping & Delivery',
  marketing: 'Marketing Tools',
  advanced: 'Later Add-on'
};
